module.exports = {
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        black: "var(--black)",
        "black-100": "var(--black-100)",
        "black-80": "var(--black-80)",
        "blue-50": "var(--blue-50)",
        "blue-text1": "var(--blue-text1)",
        bluee: "var(--bluee)",
        "brand-5": "var(--brand-5)",
        "brand-60": "var(--brand-60)",
        "color-1": "var(--color-1)",
        "color-2": "var(--color-2)",
        "destructive-50": "var(--destructive-50)",
        "gray-20": "var(--gray-20)",
        "gray-30": "var(--gray-30)",
        "gray-40": "var(--gray-40)",
        "gray-60": "var(--gray-60)",
        "gray-80": "var(--gray-80)",
        "gray0-white": "var(--gray0-white)",
        "light-blue": "var(--light-blue)",
        orange: "var(--orange)",
        primarry: "var(--primarry)",
        "purple-50": "var(--purple-50)",
        "success-50": "var(--success-50)",
        "text-2": "var(--text-2)",
        "warning-50": "var(--warning-50)",
        white: "var(--white)",
        "white-1": "var(--white-1)",
        "white-100": "var(--white-100)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "12-regular": "var(--12-regular-font-family)",
        "14-regular": "var(--14-regular-font-family)",
        "14-semibold": "var(--14-semibold-font-family)",
        "24-semibold": "var(--24-semibold-font-family)",
        "paragraph-sm": "var(--paragraph-sm-font-family)",
        "text-md-bold": "var(--text-md-bold-font-family)",
        "text-md-medium": "var(--text-md-medium-font-family)",
        "text-sm-bold": "var(--text-sm-bold-font-family)",
        "text-sm-medium": "var(--text-sm-medium-font-family)",
        "text-xs-medium": "var(--text-xs-medium-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        "focus-ring-brand": "var(--focus-ring-brand)",
        "shadow-md": "var(--shadow-md)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
  darkMode: ["class"],
};
